### PR TITLE
Fix URI encoding of special characters by replacing encodeURI with encodeURIComponent

### PR DESCRIPTION
**Pull request by jelolul**
Items with names like "Dreams & Nightmares Case" and "Copenhagen 2024 Viewer Pass + 3 Souvenir Tokens" didn't get encoded properly with `encodeURI`, making the prices `null`, since `encodeURI` is used for encoding full URLs.

### CODE REVIEW

**Comment by jelolul** [comment]
should probably update the prices after merge since mine are in GBP

**Review by ByMykel — APPROVED** [review]
Thank you ❤️

**Comment by ByMykel** [comment]
@jelolul Can you remove your las commit, so I can merge it easily?

**Comment by jelolul** [comment]
Done 🙂

**Pull request merged**
